apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: default
data:
  default.conf: |-
    server {
        listen 80;
        location / {
            proxy_pass http://pokemon-service-cip/pokemons;
        }
    }
